// ✅ Static data file — no API needed, works on Vercel/GitHub Pages
// Place this file at: client/src/lib/data.ts

export const coursesData = [
  {
    id: 1,
    title: "Drone Rules & Regulations",
    description: "Comprehensive course covering DGCA guidelines, licensing requirements, and airspace classification for commercial and recreational drone operations.",
    category: "drone",
    duration: "4 weeks",
    format: "hybrid",
    prerequisites: "Basic understanding of aviation concepts",
    learningOutcomes: [
      "Understand DGCA regulations and compliance requirements",
      "Navigate airspace classification and restrictions",
      "Complete licensing and certification processes",
      "Implement safety protocols for drone operations",
    ],
    modules: [
      "Introduction to DGCA Guidelines",
      "Airspace Classification and Restrictions",
      "Licensing and Certification Requirements",
      "Safety Protocols and Risk Management",
      "Legal Framework and Compliance",
    ],
    targetAudience: "Drone operators, pilots, and aerospace professionals",
    price: 15000,
    featured: true,
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Drone Components & Systems",
    description: "In-depth study of drone components including ESCs, motors, frames, batteries, and sensors with hands-on assembly experience.",
    category: "drone",
    duration: "6 weeks",
    format: "in-person",
    prerequisites: "Basic electronics knowledge",
    learningOutcomes: [
      "Identify and understand key drone components",
      "Assemble and configure drone systems",
      "Troubleshoot common hardware issues",
      "Select appropriate components for specific applications",
    ],
    modules: [
      "Frame Design and Materials",
      "Propulsion Systems: Motors and Propellers",
      "Electronic Speed Controllers (ESCs)",
      "Battery Technology and Power Management",
      "Sensors and Navigation Systems",
      "Communication and Control Systems",
    ],
    targetAudience: "Engineers, technicians, and drone enthusiasts",
    price: 25000,
    featured: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Aerodynamics Fundamentals",
    description: "Essential aerodynamics concepts including lift, drag, thrust, airfoils, and flow dynamics with practical applications.",
    category: "design-simulation",
    duration: "8 weeks",
    format: "online",
    prerequisites: "Mathematics and physics background",
    learningOutcomes: [
      "Master fundamental aerodynamic principles",
      "Analyze airfoil characteristics and performance",
      "Understand flow dynamics and boundary layers",
      "Apply aerodynamic concepts to aircraft design",
    ],
    modules: [
      "Introduction to Fluid Mechanics",
      "Airfoil Theory and Design",
      "Lift and Drag Analysis",
      "Boundary Layer Theory",
      "Compressible Flow Fundamentals",
      "Aircraft Performance Analysis",
    ],
    targetAudience: "Aerospace engineers and design professionals",
    price: 20000,
    featured: false,
    createdAt: new Date(),
  },
  {
    id: 4,
    title: "Ansys CFD Simulation",
    description: "Comprehensive training in computational fluid dynamics using Ansys software for aerospace applications.",
    category: "design-simulation",
    duration: "10 weeks",
    format: "hybrid",
    prerequisites: "Aerodynamics fundamentals and CAD experience",
    learningOutcomes: [
      "Master Ansys CFD software interface and tools",
      "Set up and run complex fluid simulations",
      "Analyze and interpret simulation results",
      "Optimize designs based on CFD analysis",
    ],
    modules: [
      "Ansys CFD Interface and Setup",
      "Mesh Generation and Quality",
      "Boundary Conditions and Solver Settings",
      "Turbulence Modeling",
      "Post-processing and Results Analysis",
      "Design Optimization Techniques",
    ],
    targetAudience: "Design engineers and simulation specialists",
    price: 35000,
    featured: true,
    createdAt: new Date(),
  },
];

export const articlesData = [
  {
    id: 1,
    title: "Latest Advances in Drone Propulsion Systems",
    excerpt: "Exploring breakthrough technologies in electric propulsion and their impact on drone efficiency and performance.",
    content: "The aerospace industry is witnessing unprecedented advances in drone propulsion systems...",
    category: "technology",
    author: "Dr. Rajesh Kumar",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?ixlib=rb-4.0.3",
    publishedAt: new Date(),
  },
  {
    id: 2,
    title: "New DGCA Guidelines for Commercial Drone Operations",
    excerpt: "Understanding the latest regulatory changes and their implications for commercial drone operators in India.",
    content: "The Directorate General of Civil Aviation (DGCA) has recently updated its guidelines...",
    category: "regulations",
    author: "Priya Sharma",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?ixlib=rb-4.0.3",
    publishedAt: new Date(),
  },
  {
    id: 3,
    title: "Mastering CFD Analysis: Essential Skills for Aerospace Engineers",
    excerpt: "A comprehensive guide to computational fluid dynamics and its applications in modern aerospace design.",
    content: "Computational fluid dynamics has become an indispensable tool...",
    category: "education",
    author: "Prof. Anita Desai",
    featured: false,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3",
    publishedAt: new Date(),
  },
];

export const teamMembersData = [
  {
    id: 1,
    name: "Dr. Rajesh Kumar",
    position: "Founder & Chief Technology Officer",
    bio: "Dr. Kumar brings over 15 years of experience in aerospace engineering with specialization in propulsion systems and drone technology.",
    qualifications: ["Ph.D. Aerospace Engineering, IIT Bombay", "M.Tech Propulsion Technology", "B.Tech Mechanical Engineering"],
    specialties: ["Drone Propulsion Systems", "Aerodynamics", "DGCA Compliance", "Project Management"],
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=300&h=300&fit=crop",
  },
  {
    id: 2,
    name: "Priya Sharma",
    position: "Head of Training & Curriculum",
    bio: "Priya is a seasoned educator with expertise in aerospace design and simulation technologies, focusing on practical learning approaches.",
    qualifications: ["M.Tech Aerospace Engineering", "PMP Certification", "B.Tech Aeronautical Engineering"],
    specialties: ["Ansys Simulation", "CAD Design", "Curriculum Development", "Training Delivery"],
    imageUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b1e0?ixlib=rb-4.0.3&w=300&h=300&fit=crop",
  },
  {
    id: 3,
    name: "Prof. Anita Desai",
    position: "Senior Consultant & Advisor",
    bio: "Prof. Desai is a distinguished academic and industry expert with extensive experience in aerospace research and consultancy.",
    qualifications: ["Ph.D. Computational Fluid Dynamics", "M.S. Aerospace Engineering", "B.S. Mechanical Engineering"],
    specialties: ["CFD Analysis", "Research & Development", "Industry Partnerships", "Technical Advisory"],
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&w=300&h=300&fit=crop",
  },
];

export const testimonialsData = [
  {
    id: 1,
    name: "Sarah Johnson",
    position: "Aerospace Engineer",
    company: "SkyTech Industries",
    content: "The drone design course completely transformed my understanding of aerodynamics. The hands-on Ansys simulations were invaluable for my career transition into aerospace engineering.",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=100&h=100&fit=crop",
  },
  {
    id: 2,
    name: "Michael Chen",
    position: "CTO",
    company: "Dronetech Solutions",
    content: "Their consultancy services helped us achieve DGCA compliance seamlessly. The team's expertise in regulatory requirements is unmatched.",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&w=100&h=100&fit=crop",
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    position: "Aerospace Consultant",
    company: "Independent",
    content: "The comprehensive curriculum and practical approach gave me the confidence to launch my own aerospace consulting firm. Highly recommended!",
    featured: true,
    imageUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b1e0?ixlib=rb-4.0.3&w=100&h=100&fit=crop",
  },
];